# Generated by Django 4.2.2 on 2023-06-27 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('pet_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('age', models.IntegerField()),
                ('type', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='PetAppointment',
            fields=[
                ('date', models.DateField()),
                ('medical_specialty', models.CharField(max_length=30)),
                ('pet_appointment_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('mail', models.EmailField(max_length=254)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PetApp.pet')),
            ],
        ),
        migrations.AddField(
            model_name='pet',
            name='pet_appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PetApp.petappointment'),
        ),
    ]
